# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  rp-st-automation

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:  
  # This is the Lambda function definition associated with the source code: sqs-payload-logger.js. For all available properties, see
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  ScheduledEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Handler: src/handlers/rp-st-automation.handler
      # This property associates this Lambda function with a scheduled CloudWatch Event. For all available properties, see
      # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
      # This example runs every hour.
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *)
      MemorySize: 128
      Timeout: 600
      Environment:
        Variables:
          DB_NAME: vapor
          DB_USER: cmlali
          DB_HOST: qa-mongoose.ckcv0ldemjbo.us-east-2.rds.amazonaws.com
          DB_PORT: 3306
          DB_PASSWORD: nshQKYpBscmMSahCySS0IUvYkPIMFjW8dJTFncH9pc8Rejq
          PDFGENERATOR_SECRET: e913768c16ae820ce7d13ee247c1dcbee5b9357bfe39ad4eda6d5a7bc0bedd70
          PDFGENERATOR_API_KEY: 79791e4996ff7bdf873fd38d4ca2fec42c9a92db162438c4d057f416fb59fdf0
          PDFGENERATOR_WORKSPACE_ID: ali.maqsood93@gmail.com
          RP_PASSWORD: P@$$w0rd
          RP_USERNAME: alitest123@yopmail.com
          S3_BUCKET_NAME: storage-qa-mongoose-br2wu78v1.rocketplantech.com
          ST_CLIENT_ID: cid.mvbp31sh9xpdd4gnq8t4mg6u4
          ST_CLIENT_SECRET: cs1.tx75mexv0vqtyclzpmj7u5r775somry21gxg6ybki416kqghkg
          ST_APP_KEY: ak1.3att89vhhsoeulmdls0drgtje